all:mirror_rotate_tree binary_tree_to_list right_down_go

.PHONY:all clean

mirror_rotate_tree:
	gcc -g -Wall -Wextra  $@.c -o $@
binary_tree_to_list:
	gcc -g -Wall -Wextra  $@.c -o $@
right_down_go:
	gcc -g -Wall -Wextra $@.c -o $@
clean:
	rm  mirror_rotate_tree binary_tree_to_list right_down_go
