all:search_tree avl_tree
.PHONY:clean
search_tree:
	gcc -g -Wall -Wextra  search_tree_test.c search_tree.c -o $@
avl_tree:
	g++ -g -Wall -Wextra avl_tree.c avl_tree_test.c -o $@
clean:
	rm searh_tree
